/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as CentersIndexRouteImport } from './routes/centers/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ShopCheckoutRouteImport } from './routes/shop/checkout'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopProductIdRouteImport } from './routes/shop/$productId'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalReturnsRouteImport } from './routes/legal/returns'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as CentersCenterIdRouteImport } from './routes/centers/$centerId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'

const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersIndexRoute = CentersIndexRouteImport.update({
  id: '/centers/',
  path: '/centers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/shop/cart',
  path: '/shop/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReturnsRoute = LegalReturnsRouteImport.update({
  id: '/legal/returns',
  path: '/legal/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersCenterIdRoute = CentersCenterIdRouteImport.update({
  id: '/centers/$centerId',
  path: '/centers/$centerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/donate': typeof DonateRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/centers/$centerId': typeof CentersCenterIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/blog': typeof BlogIndexRoute
  '/centers': typeof CentersIndexRoute
  '/events': typeof EventsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/donate': typeof DonateRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/centers/$centerId': typeof CentersCenterIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/blog': typeof BlogIndexRoute
  '/centers': typeof CentersIndexRoute
  '/events': typeof EventsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/donate': typeof DonateRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/centers/$centerId': typeof CentersCenterIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/blog/': typeof BlogIndexRoute
  '/centers/': typeof CentersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/donate'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/$slug'
    | '/centers/$centerId'
    | '/events/$eventId'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/terms'
    | '/shop/$productId'
    | '/shop/cart'
    | '/shop/checkout'
    | '/blog'
    | '/centers'
    | '/events'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/donate'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/$slug'
    | '/centers/$centerId'
    | '/events/$eventId'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/terms'
    | '/shop/$productId'
    | '/shop/cart'
    | '/shop/checkout'
    | '/blog'
    | '/centers'
    | '/events'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/donate'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/$slug'
    | '/centers/$centerId'
    | '/events/$eventId'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/terms'
    | '/shop/$productId'
    | '/shop/cart'
    | '/shop/checkout'
    | '/blog/'
    | '/centers/'
    | '/events/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  DonateRoute: typeof DonateRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CentersCenterIdRoute: typeof CentersCenterIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalReturnsRoute: typeof LegalReturnsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CentersIndexRoute: typeof CentersIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers/': {
      id: '/centers/'
      path: '/centers'
      fullPath: '/centers'
      preLoaderRoute: typeof CentersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/shop/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/returns': {
      id: '/legal/returns'
      path: '/legal/returns'
      fullPath: '/legal/returns'
      preLoaderRoute: typeof LegalReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers/$centerId': {
      id: '/centers/$centerId'
      path: '/centers/$centerId'
      fullPath: '/centers/$centerId'
      preLoaderRoute: typeof CentersCenterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  DonateRoute: DonateRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  BlogSlugRoute: BlogSlugRoute,
  CentersCenterIdRoute: CentersCenterIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalReturnsRoute: LegalReturnsRoute,
  LegalTermsRoute: LegalTermsRoute,
  ShopProductIdRoute: ShopProductIdRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  BlogIndexRoute: BlogIndexRoute,
  CentersIndexRoute: CentersIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
